import Navbar from "./components/navbar/navbar";

export const metadata = {
  title: "localhost:3000",
  description: "Generated by Next.js"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>

        {children}
      </body>
    </html>
  );
}
